# Generated by Django 4.0.4 on 2022-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='working_hours',
            field=models.CharField(choices=[('6h', '6h'), ('7h', '7h'), ('8h', '8h'), ('9h', '9h'), ('10h', '10h')], max_length=200, null=True),
        ),
    ]
