# Generated by Django 4.0.4 on 2022-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='job_roll',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='works_status',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-Site', 'On-Site'), ('Hybrid', 'Hybrid')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('Intern', 'Intern'), ('6 months', '6 months'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('4 Year', '4 Year'), ('5 Year', '5 Year'), ('6 Year', '6 Year'), ('6+', '6+')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Big data engineer', 'Big data engineer'), ('DevOps Engineer', 'DevOps Engineer'), ('Information systems security manager', 'Information systems security manager'), ('Mobile applications developer', 'Mobile applications developer'), ('Database manager', 'Database manager'), ('Data scientist', 'Data scientist'), ('Network/cloud engineer', 'Network/cloud engineer')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='no_of_applicants',
            field=models.CharField(choices=[('1-5', '1-5'), ('5-10', '5-10'), ('10-20', '10-20'), ('20-50', '20-50'), ('50+', '50+')], max_length=200, null=True),
        ),
    ]
