# Generated by Django 4.0.4 on 2022-04-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_job_roll_vacancy_works_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='graduate_status',
            field=models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduate'), ('P', 'Post-Graduate')], max_length=128),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_status',
            field=models.CharField(choices=[('F', 'Full-Time'), ('P', 'Part-Time')], max_length=128),
        ),
    ]
