# Generated by Django 4.0.4 on 2022-04-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancy_graduate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='graduate_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
