# Generated by Django 4.0.4 on 2022-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_graduate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='about_company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='addressEssentional_duties_responsibilities',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='educational_requrements',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
