# Generated by Django 4.0.4 on 2022-04-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_rename_addressessentional_duties_responsibilities_vacancy_essentional_duties_responsibilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='educational_requrements',
            new_name='educational_requirements',
        ),
    ]
